export const ADD_TODO_ITEM_PENDING = "ADD_TODO_ITEM_PENDING";
export const ADD_TODO_ITEM_SUCCESS = "ADD_TODO_ITEM_SUCCESS";
export const ADD_TODO_ITEM_FAILURE = "ADD_TODO_ITEM_FAILURE";

export const DELETE_TODO_ITEM_PENDING = "DELETE_TODO_ITEM_PENDING";
export const DELETE_TODO_ITEM_SUCCESS = "DELETE_TODO_ITEM_SUCCESS";
export const DELETE_TODO_ITEM_FAILURE = "DELETE_TODO_ITEM_FAILURE";

export const TOGGLE_TODO_ITEM_PENDING = "TOGGLE_TODO_ITEM_PENDING";
export const TOGGLE_TODO_ITEM_SUCCESS = "TOGGLE_TODO_ITEM_SUCCESS";
export const TOGGLE_TODO_ITEM_FAILURE = "TOGGLE_TODO_ITEM_FAILURE";
